data_path: "knauf_innenwande_tender_data/long_tender_innenwande_de.csv"
llm_url: "http://localhost:11434"
# llm_name: "zephyr-tender-text"
# embedding_model: "sentence-transformers/all-mpnet-base-v2"
# qdrant_url: "http://localhost:6333"
llm_name: "gpt-3.5-turbo"
embedding_model: "nomic-ai/nomic-embed-text-v1.5"
collection_name: "tendertext_short"
chunk_size: 1024

milvus:
  uri: "./milvus_innenwande_tender_fastapi.db"
  dim: 768
  overwrite: false
  enable_sparse: true
  hybrid_ranker: "RRFRanker"
  hybrid_ranker_params: 
    k: 50
  verbose: true