data_path: "data/long_tender_innenwande_de.csv"
llm_url: "http://localhost:11434"
# llm_name: "zephyr-tender-text"
# embedding_model: "sentence-transformers/all-mpnet-base-v2"
# qdrant_url: "http://localhost:6333"
llm_name: "gpt-3.5-turbo"
embedding_model: "nomic-ai/nomic-embed-text-v1.5"
collection_name: "tendertext_short"
chunk_size: 1024
fastapi_url: "http://127.0.0.1:8000/api/search"
telemetry_url: "http://127.0.0.1:6006/v1/traces"
milvus:
  uri: "rag_tender_export_fastapi/DB/milvus_innenwande_tender_fastapi.db"
  dim: 768
  overwrite: false
  enable_sparse: true
  hybrid_ranker: "RRFRanker"
  hybrid_ranker_params: 
    k: 50
  verbose: true