deep_set: "mixedbread-ai/deepset-mxbai-embed-de-large-v1"
deep_set_dim: 1024

nomic: "nomic-ai/nomic-embed-text-v1.5"
nomic_dim: 768

# reranker_model: "mixedbread-ai/deepset-mxbai-embed-de-large-v1"
# reranker_model: "cross-encoder/quora-roberta-base-multilingual"
reranker_model: "cross-encoder/ms-marco-MiniLM-L-2-v2"
llamatrace_url: "https://llamatrace.com/projects/UHJvamVjdDox"
data_path: "data/long_tender_innenwande_de.csv"
llm_url: "http://localhost:11434"
# llm_name: "zephyr-tender-text"
# embedding_model: "sentence-transformers/all-mpnet-base-v2"
# qdrant_url: "http://localhost:6333"
llm_name: "gpt-3.5-turbo"
embedding_model: "mixedbread-ai/deepset-mxbai-embed-de-large-v1"
collection_name: "tendertext_short"
chunk_size: 1024
fastapi_url: "http://127.0.0.1:8000/api/search"
enable_tracing: true
telemetry_url: "http://127.0.0.1:6006/v1/traces"
milvus:
  uri: "src/DB/milvus_innenwande_tender_fastapi.db"
  dim: 1024
  overwrite: false
  enable_sparse: true
  hybrid_ranker: "RRFRanker"
  hybrid_ranker_params:
    k: 50
  verbose: true