name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Railway
      run: railway login --apiKey ${{ secrets.RAILWAY_TOKEN }}

    - name: Deploy to Railway
      run: railway up --service "$RAILWAY_SERVICE_NAME" --detach